services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    environment:
      - PASSWORD=set_in_env  # Set the password for Jupyter notebook
    command: "start-notebook.sh --NotebookApp.token=${PASSWORD}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

