services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN
      - VLLM_API_KEY
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_ENDPOINT_URL
    ports:
      - "8000:8000"
    ipc: host
    command: --model ${HUGGING_FACE_MODEL}

