services:
  vllm:
    image: vllm/vllm-openai:latest
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /cudo/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN
      - VLLM_API_KEY

    ports:
      - "8000:8000"
    ipc: host
    command: --model ${HUGGING_FACE_MODEL}

