services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    volumes:
      - /cudo:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter
    environment:
      - AUTH_TOKEN=CUDO_TOKEN
      - GEN_CERT=yes
    command: "start-notebook.sh --NotebookApp.token="
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

