services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 127.0.0.1:11434:11434
    container_name: ollama
    networks:
      - ollama-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  nginx-auth:
    image: nginx
    container_name: nginx-auth
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - AUTH_TOKEN=set_in_env
    networks:
      - ollama-net

networks:
  ollama-net:
    driver: bridge